### PR TITLE
Store all aws configs in .secrets

### PR DESCRIPTION
**Pull request by gordonje**
Currently, devs working locally can have the various aws configurations in two different places: 
1. A .secrets shell script similar to the one we create on the EC2 instance, which can be sourced to load these configurations as environment variables. 
2. A aws_config.py file that, when imported, adds these configurations to the fabric env. This is the file that is manipulated by various fab functions.

This setup allows the key pair files and EC2 and RDS instances to be dynamic (which has been great for spinning up and terminating instances with various configs, as we continue to figure that out).

However, this set up also allows the most recently created RDS host to get out of sync with the RDS host referenced in the developer's environment, which is what django recognizes (in settings.py). As far, I can tell, there's no way for Python or Fabric to permanently set these environment variables (it was a rather n00b assumption on my part that this would be possible).

This pull request resolves this issue by storing all of these configurations in ~/.secrets and reading those configurations from that file into the fabric env. 

One potential downside: The developer's local .secrets file will need additional configurations (specifically, EC2_HOST and KEY_NAME) that will not be included in the version of this file on the EC2 instance. 

Still, it's possibly a less hacky and simpler approach that what we are currently doing, but would like other eyes on this before merging.

### CODE REVIEW

**Comment by palewire** [comment]
I think this is a good move because it takes a step in the direction of greater simplicity. For that reason alone, I say go for it.

After a little online research, two rough thoughts for taking it further that came to me:
1. Convert the `.secrets` files to the `.env` namespace and standard popularized by the "12 factor" school of development. There's a [django-dotenv](https://github.com/jpadilla/django-dotenv) application that could be potentially used to import the settings in manage.py, removing the need to otherwise pump it into the Django app with virtualenv.
2. Determine if we can edit the .env file more fluidly inside Flask using Python's built-in [ConfigParser](https://docs.python.org/2.7/library/configparser.html) library. If we can, it might be possible to Fabric read-and-write the configuration file as needed and avoid issues.

**Comment by palewire** [comment]
I just pushed some fixes to the merge conflicts. Not sure I nailed and will try to finesse a little more along the lines of what I suggested.

**Comment by palewire** [comment]
Alright. I believe I have refactored this branch enough to have met my two goals as far as managing the configuration, creating a new key, creating an RDS instance and spinning up a development environment.

What remains to be figured out for this idea to be viable:
- [x] Expand the refactor to include the EC2 instance creation
- [ ] Integrate the new .env file into the Chef cookbook and instance configuration process

**Comment by palewire** [comment]
Alrighty. I think I have it spinning up the server. Now the last and hardest step. Getting the chef bootstrap to take. 

I suspect that I just need to figure out a way to write out a .env file in the prod environment and I'll be good. 

It might be good to expand the local fabric functions for that to allow for editing the remote file as well.

**Comment by gordonje** [comment]
@palewire Added a fab function to copy the local .env file to the server. Calling that in the bootstrap function, but it can also be used to re-synchronize the remote config with the local dev config after the fact.

Does that work?

**Comment by palewire** [comment]
It's looking good to me. I might monkey around a little more but I think we've almost got it.

**Comment by palewire** [comment]
Alrighty. I think I roughed my way through the whole pipeline and it's working. I also did a little reorganization of the Django project and got the unittests passing on TravisCI. Time to merge I guess.

**Pull request merged**
